# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  port: 3306
  username: root
  password: 1234

development:
  <<: *default
  database: bulletinboardruby
  encoding: utf8mb4
  collation: utf8mb4_polish_ci

# Warning: The database defined as "test" will be erased and
test:
  <<: *default
  database: bulletinboardruby
  encoding: utf8mb4
  collation: utf8mb4_polish_ci

production:
  <<: *default
  database: bulletinboardruby
  encoding: utf8mb4
  collation: utf8mb4_polish_ci